// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_z7-FPGDHzlncowiPPlh1FODgIBGgIbg',
    appId: '1:894696116565:android:0260a14b8a0c8ff76f5fdc',
    messagingSenderId: '894696116565',
    projectId: 'ehelpdesk-ueu',
    storageBucket: 'ehelpdesk-ueu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApjZGWw2XDA0rEiOmg1C6jkhMel8B0K0k',
    appId: '1:894696116565:ios:18c93dc956fb93b16f5fdc',
    messagingSenderId: '894696116565',
    projectId: 'ehelpdesk-ueu',
    storageBucket: 'ehelpdesk-ueu.appspot.com',
    androidClientId: '894696116565-0nevnfegd8gq7m340sik9829t9nf92ab.apps.googleusercontent.com',
    iosClientId: '894696116565-3dbtdj800ee42tmrn9fj9ov9v3sirsi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ehelpdesk',
  );
}
